### ISSUE TITLE
put data before an interest is received

### ISSUE THREAD

**Issue by astralien3000** [named-data-iot/ndn-riot#7]
The aim is to put data in the cache when it is generated, even if no interest message have been received.
Is that even an acceptable behaviour ?
Currently, if the data don't match anything in the pit, the data is discarded.

**Comment by wentaoshang** [comment]
The earlier versions of NDN forwarders (ccnd and nfd) support this behavior, but it is considered a hack and may open a door for DDoS attack where the attacker keeps shooting unrequested data to the victim and fill up the victim's cache table.

In principle, the application should implement its own data store to hold the pre-generated data, instead of (ab)using the NDN stack's cache table. Also, the cached data may be removed from the cache table at any time. So the application is ultimately responsible for maintaining its data anyway.

**Comment by astralien3000** [comment]
Ok thanks for the explanations !
